{% set name = "pyshortcuts" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshortcuts-{{ version }}.tar.gz
  sha256: 5791056a57f5dc71225afa99838c13354ba00d05568f0e069bb59c2376cc6701

build:
  number: 0
  entry_points:
    - pyshortcut = pyshortcuts:shortcut_cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pywin32  # [win]

test:
  imports:
    - pyshortcuts
  commands:
    - pip check
    - pyshortcut --help
  requires:
    - pip

about:
  home: http://github.com/newville/pyshortcuts
  summary: create desktop and Start Menu shortcuts for python scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
